# title: Andrea Lopera
logo: /assets/Profile_Andee.png
description: 
"I am a professional with a diverse background, driven by a passion for problem-solving and making a positive impact. 
My career journey began in Industrial Engineering, where I spent six years sharpening my analytical skills in various production-related 
roles and using data analysis to boost output and efficiency. Seeking to make a broader and more meaningful contribution to the 
world, I then shifted to education, earning Bachelor’s and Master’s degrees in Math Education. Though my experience as an educator
was brief, it deepened my understanding of how transformative knowledge can be. Realizing my interests lay at the crossroads of 
mathematics, data, and societal change, I transitioned into data science, gaining a certification in Applied Data Science, 
and am currently working toward a Master's degree in the field. This path has allowed me to combine my love for numbers with a career focused on positive change. I am excited about the endless opportunities in data science and look forward to using my skills to drive innovation and solve complex challenges, 
bringing together my analytical expertise, educational background, and commitment to making a difference."
show_downloads: true
theme: jekyll-theme-minima
